const MESSAGE_LIST_ACTIONS = {
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_ERROR: 'GET_MESSAGES_ERROR',
    GET_MESSAGES_LOADING: 'GET_MESSAGES_LOADING',
    DELETE_MESSAGE: 'DELETE_MESSAGE'
};

export { MESSAGE_LIST_ACTIONS };
