const MESSAGE_LIST_ACTIONS = {
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_ERROR: 'GET_MESSAGES_ERROR',
    GET_MESSAGES_LOADING: 'GET_MESSAGES_LOADING'
};

export { MESSAGE_LIST_ACTIONS };
